/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-09 07:59:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"header-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"top-nav-left\">\r\n");
      out.write("                <a href=\"#\" class=\"top-link\">\r\n");
      out.write("                    <i class=\"fas fa-gift\"></i>\r\n");
      out.write("                    이벤트\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"top-link\">\r\n");
      out.write("                    <i class=\"fas fa-question-circle\"></i>\r\n");
      out.write("                    자주 묻는 질문\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top-nav-right\">\r\n");
      out.write("                <div class=\"language-selector\">\r\n");
      out.write("                    <img src=\"https://flagcdn.com/w20/kr.png\" alt=\"한국\" width=\"20\">\r\n");
      out.write("                    <span>대한민국 - 한국어</span>\r\n");
      out.write("                    <i class=\"fas fa-chevron-down\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"#\" class=\"top-link\">\r\n");
      out.write("                    <i class=\"fas fa-user\"></i>\r\n");
      out.write("                    회원가입\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"header-main\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <svg width=\"180\" height=\"45\" viewBox=\"0 0 180 45\">\r\n");
      out.write("                    <!-- 대한항공 로고 -->\r\n");
      out.write("                    <g>\r\n");
      out.write("                        <!-- 외부 원 테두리 -->\r\n");
      out.write("                        <circle cx=\"22.5\" cy=\"22.5\" r=\"18\" fill=\"none\" stroke=\"#003876\" stroke-width=\"2.5\"/>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- 태극 심볼 - 심플 버전 -->\r\n");
      out.write("                        <g transform=\"translate(22.5, 22.5) rotate(90) scale(-1, 1)\">\r\n");
      out.write("                            <!-- 배경 원 (빨간색) -->\r\n");
      out.write("                            <circle cx=\"0\" cy=\"0\" r=\"15\" fill=\"#CD212A\"/>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- S자 모양의 파란색 영역 -->\r\n");
      out.write("                            <path d=\"M 0,-15 A 7.5,7.5 0 0,1 0,0 A 7.5,7.5 0 0,0 0,15 A 15,15 0 0,1 0,-15\" fill=\"#003876\"/>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- 작은 빨간색 원 (하단) -->\r\n");
      out.write("                            <circle cx=\"0\" cy=\"7.5\" r=\"7.5\" fill=\"#CD212A\"/>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- 작은 파란색 원 (상단) -->\r\n");
      out.write("                            <circle cx=\"0\" cy=\"-7.5\" r=\"7.5\" fill=\"#003876\"/>\r\n");
      out.write("                        </g>\r\n");
      out.write("                    </g>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- KOREAN AIR 텍스트 -->\r\n");
      out.write("                    <text x=\"55\" y=\"28\" font-family=\"'Nanum Gothic', Arial, sans-serif\" font-size=\"18\" font-weight=\"bold\" fill=\"#003876\" letter-spacing=\"1px\">KOREAN AIR</text>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"main-nav\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link\">예약</a>\r\n");
      out.write("                        <div class=\"dropdown-menu\">\r\n");
      out.write("                            <div class=\"dropdown-content\">\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>항공권 예약</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">항공편 검색</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">다구간 예약</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">그룹 예약</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">특가 항공권</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>예약 관리</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">예약 조회/변경</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">좌석 선택</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">기내식 선택</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">수하물 추가</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>부가 서비스</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">호텔 예약</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">렌터카 예약</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">여행자 보험</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">공항 라운지</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link\">여행 준비</a>\r\n");
      out.write("                        <div class=\"dropdown-menu\">\r\n");
      out.write("                            <div class=\"dropdown-content\">\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>체크인</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">온라인 체크인</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">모바일 체크인</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">탑승권 출력</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">좌석 변경</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>여행 정보</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">공항 정보</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">비자/여권 정보</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">수하물 규정</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">기내 반입 금지품목</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>특별 서비스</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">특별 도움 서비스</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">반려동물 동반</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">임산부 서비스</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">어린이 혼자 여행</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link\">스카이패스</a>\r\n");
      out.write("                        <div class=\"dropdown-menu\">\r\n");
      out.write("                            <div class=\"dropdown-content\">\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>마일리지</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">마일리지 조회</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">마일리지 적립</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">마일리지 사용</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">마일리지 양도</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>등급 혜택</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">회원 등급 안내</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">등급별 혜택</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">라운지 이용</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">우선 탑승</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-column\">\r\n");
      out.write("                                    <h4>파트너 혜택</h4>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">제휴 카드</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">호텔 파트너</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">렌터카 파트너</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">쇼핑몰 파트너</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"header-actions\">\r\n");
      out.write("                <div class=\"search-box\">\r\n");
      out.write("                    <input type=\"text\" placeholder=\"궁금한 것을 검색해 보세요!\">\r\n");
      out.write("                    <button class=\"search-btn\">\r\n");
      out.write("                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"login-btn\">로그인</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
