/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-09 07:05:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes\">\r\n");
      out.write("    <!-- 웹페이지 최소 너비 576px 보장을 위한 추가 메타 태그 -->\r\n");
      out.write("    <meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("    <title>항공사 웹사이트</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 모듈화된 헤더 포함 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"booking-widget\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"booking-card\">\r\n");
      out.write("                <div class=\"booking-tabs\">\r\n");
      out.write("                    <button class=\"tab-btn active\" data-tab=\"flight\">항공권 예매</button>\r\n");
      out.write("                    <button class=\"tab-btn\" data-tab=\"checkin\">예약 조회</button>\r\n");
      out.write("                    <button class=\"tab-btn\" data-tab=\"schedule\">체크인</button>\r\n");
      out.write("                    <button class=\"tab-btn\" data-tab=\"status\">출도착/스케줄</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"booking-content active\" id=\"flight\">\r\n");
      out.write("                    <div class=\"trip-type-section\">\r\n");
      out.write("                        <div class=\"trip-type-buttons\">\r\n");
      out.write("                            <button class=\"trip-type-btn active\" data-type=\"round\">왕복</button>\r\n");
      out.write("                            <button class=\"trip-type-btn\" data-type=\"oneway\">편도</button>\r\n");
      out.write("                            <button class=\"trip-type-btn\" data-type=\"multi\">다구간</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"special-options\">\r\n");
      out.write("                            <label class=\"checkbox-label\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"award-ticket\">\r\n");
      out.write("                                <span class=\"checkmark\"></span>\r\n");
      out.write("                                가까운 날짜 함께 조회\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"route-section\">\r\n");
      out.write("                        <div class=\"route-inputs\">\r\n");
      out.write("                            <div class=\"airport-input departure\">\r\n");
      out.write("                                <div class=\"airport-code\">SEL</div>\r\n");
      out.write("                                <div class=\"airport-name\">서울</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button class=\"swap-route-btn\">\r\n");
      out.write("                                <i class=\"fas fa-exchange-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <div class=\"airport-input arrival\">\r\n");
      out.write("                                <div class=\"airport-code\">To</div>\r\n");
      out.write("                                <div class=\"airport-name\">도착지</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"booking-details\">\r\n");
      out.write("                        <div class=\"date-section\">\r\n");
      out.write("                            <div class=\"date-input\">\r\n");
      out.write("                                <label>출발일</label>\r\n");
      out.write("                                <input type=\"date\" value=\"2025-05-28\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"passenger-section\">\r\n");
      out.write("                            <div class=\"passenger-input\">\r\n");
      out.write("                                <label>탑승객</label>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>성인 1명</option>\r\n");
      out.write("                                    <option>성인 2명</option>\r\n");
      out.write("                                    <option>성인 3명</option>\r\n");
      out.write("                                    <option>성인 4명</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"class-section\">\r\n");
      out.write("                            <div class=\"class-input\">\r\n");
      out.write("                                <label>좌석 등급</label>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>선택하세요</option>\r\n");
      out.write("                                    <option>일반석</option>\r\n");
      out.write("                                    <option>비즈니스석</option>\r\n");
      out.write("                                    <option>일등석</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"search-section\">\r\n");
      out.write("                            <button class=\"search-flights-btn\">항공편 검색</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"booking-content\" id=\"checkin\">\r\n");
      out.write("                    <div class=\"checkin-form\">\r\n");
      out.write("                        <div class=\"form-description\">\r\n");
      out.write("                            <p>예약번호 또는 항공권번호</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"checkin-inputs\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"예) A1B2C3 또는 1801234567890\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <label>출발일</label>\r\n");
      out.write("                                <input type=\"date\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <label>성</label>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <label>이름</label>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"search-section\">\r\n");
      out.write("                                <button class=\"search-flights-btn\">조회</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-notice\">\r\n");
      out.write("                            <label class=\"checkbox-label\">\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                                <span class=\"checkmark\"></span>\r\n");
      out.write("                                [필수] 본인의 예약 정보이거나 승객으로부터 조회를 위임 받은 예약 정보입니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <p class=\"notice-text\">국내선 입금 예약인 경우, 입금 상태 여부를 입력하세요.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"booking-content\" id=\"schedule\">\r\n");
      out.write("                    <div class=\"schedule-form\">\r\n");
      out.write("                        <div class=\"form-description\">\r\n");
      out.write("                            <p>예약번호 또는 항공권번호</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"schedule-inputs\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"예) A1B2C3 또는 1801234567890\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <label>출발일</label>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>2025년 05월 28일</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <label>성</label>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <label>이름</label>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"search-section\">\r\n");
      out.write("                                <button class=\"search-flights-btn\">조회</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-notice\">\r\n");
      out.write("                            <label class=\"checkbox-label\">\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                                <span class=\"checkmark\"></span>\r\n");
      out.write("                                [필수] 본인의 예약 정보이거나 승객으로부터 조회를 위임 받은 예약 정보입니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <p class=\"notice-text\">국내선 입금 예약인 경우, 입금 상태 여부를 입력하세요.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"booking-content\" id=\"status\">\r\n");
      out.write("                    <div class=\"status-form\">\r\n");
      out.write("                        <div class=\"status-options\">\r\n");
      out.write("                            <button class=\"status-btn active\">출도착 조회</button>\r\n");
      out.write("                            <button class=\"status-btn\">수간 스케줄</button>\r\n");
      out.write("                            <button class=\"status-btn\">출/도착지</button>\r\n");
      out.write("                            <button class=\"status-btn\">편명</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"status-inputs\">\r\n");
      out.write("                            <div class=\"route-inputs\">\r\n");
      out.write("                                <div class=\"airport-input\">\r\n");
      out.write("                                    <div class=\"airport-code\">From</div>\r\n");
      out.write("                                    <div class=\"airport-name\">출발지</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button class=\"swap-route-btn\">\r\n");
      out.write("                                    <i class=\"fas fa-exchange-alt\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"airport-input\">\r\n");
      out.write("                                    <div class=\"airport-code\">To</div>\r\n");
      out.write("                                    <div class=\"airport-name\">도착지</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"date-input\">\r\n");
      out.write("                                <label>출발일</label>\r\n");
      out.write("                                <input type=\"date\" value=\"2025-05-28\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"search-section\">\r\n");
      out.write("                                <button class=\"search-flights-btn\">조회</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"banner\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"banner-slider\">\r\n");
      out.write("                <div class=\"slide active\" style=\"background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('https://images.unsplash.com/photo-1436491865332-7a61a109cc05?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\">\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <h2>유럽 노선 특가 이벤트</h2>\r\n");
      out.write("                        <p>꿈꾸던 유럽 여행, 지금 특별한 가격으로 만나보세요</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">자세히 보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"slide\" style=\"background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('https://images.unsplash.com/photo-1540339832862-474599807836?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\">\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <h2>프리미엄 신규 기내 서비스</h2>\r\n");
      out.write("                        <p>더욱 편안하고 특별한 여행을 위한 새로운 기내 서비스를 소개합니다</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">자세히 보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"slide\" style=\"background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('https://images.unsplash.com/photo-1464038008305-ee8def75f234?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\">\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <h2>마일리지 더블 적립 혜택</h2>\r\n");
      out.write("                        <p>이번 달 특별 프로모션, 모든 노선 마일리지 두 배 적립</p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\">자세히 보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"banner-nav\">\r\n");
      out.write("                <button class=\"prev\"><i class=\"fas fa-chevron-left\"></i></button>\r\n");
      out.write("                <div class=\"dots\">\r\n");
      out.write("                    <span class=\"dot active\"></span>\r\n");
      out.write("                    <span class=\"dot\"></span>\r\n");
      out.write("                    <span class=\"dot\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"next\"><i class=\"fas fa-chevron-right\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"features\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"feature-box\">\r\n");
      out.write("                <div class=\"feature-icon\">\r\n");
      out.write("                    <i class=\"fas fa-map-marked-alt\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3>취항지 안내</h3>\r\n");
      out.write("                <p>전 세계 40개국 120개 도시로 편리하게 여행하세요</p>\r\n");
      out.write("                <a href=\"#\" class=\"feature-link\">더 알아보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"feature-box\">\r\n");
      out.write("                <div class=\"feature-icon\">\r\n");
      out.write("                    <i class=\"fas fa-plane\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3>항공기 소개</h3>\r\n");
      out.write("                <p>최신 항공기 보유로 안전하고 쾌적한 여행을 약속합니다</p>\r\n");
      out.write("                <a href=\"#\" class=\"feature-link\">더 알아보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"feature-box\">\r\n");
      out.write("                <div class=\"feature-icon\">\r\n");
      out.write("                    <i class=\"fas fa-gift\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3>마일리지 혜택</h3>\r\n");
      out.write("                <p>다양한 적립과 사용으로 더 많은 혜택을 누리세요</p>\r\n");
      out.write("                <a href=\"#\" class=\"feature-link\">더 알아보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"feature-box\">\r\n");
      out.write("                <div class=\"feature-icon\">\r\n");
      out.write("                    <i class=\"fas fa-headset\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3>고객 지원</h3>\r\n");
      out.write("                <p>연중무휴 고객센터 운영으로 문의사항을 빠르게 해결해 드립니다</p>\r\n");
      out.write("                <a href=\"#\" class=\"feature-link\">더 알아보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"destinations\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"section-title\">인기 여행지</h2>\r\n");
      out.write("            <div class=\"destination-grid\">\r\n");
      out.write("                <div class=\"destination-card\">\r\n");
      out.write("                    <div class=\"destination-img\" style=\"background-image: url('https://images.unsplash.com/photo-1499856871958-5b9627545d1a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"destination-info\">\r\n");
      out.write("                        <h3>파리</h3>\r\n");
      out.write("                        <p class=\"price\">편도 <span>650,000원~</span></p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn-outline\">예매하기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"destination-card\">\r\n");
      out.write("                    <div class=\"destination-img\" style=\"background-image: url('https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"destination-info\">\r\n");
      out.write("                        <h3>뉴욕</h3>\r\n");
      out.write("                        <p class=\"price\">편도 <span>780,000원~</span></p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn-outline\">예매하기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"destination-card\">\r\n");
      out.write("                    <div class=\"destination-img\" style=\"background-image: url('https://images.unsplash.com/photo-1513407030348-c983a97b98d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"destination-info\">\r\n");
      out.write("                        <h3>도쿄</h3>\r\n");
      out.write("                        <p class=\"price\">편도 <span>250,000원~</span></p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn-outline\">예매하기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"destination-card\">\r\n");
      out.write("                    <div class=\"destination-img\" style=\"background-image: url('https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"destination-info\">\r\n");
      out.write("                        <h3>시드니</h3>\r\n");
      out.write("                        <p class=\"price\">편도 <span>720,000원~</span></p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn-outline\">예매하기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"destination-card\">\r\n");
      out.write("                    <div class=\"destination-img\" style=\"background-image: url('https://images.unsplash.com/photo-1528181304800-259b08848526?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"destination-info\">\r\n");
      out.write("                        <h3>방콕</h3>\r\n");
      out.write("                        <p class=\"price\">편도 <span>280,000원~</span></p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn-outline\">예매하기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"destination-card\">\r\n");
      out.write("                    <div class=\"destination-img\" style=\"background-image: url('https://images.unsplash.com/photo-1552832230-c0197dd311b5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"destination-info\">\r\n");
      out.write("                        <h3>로마</h3>\r\n");
      out.write("                        <p class=\"price\">편도 <span>680,000원~</span></p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn-outline\">예매하기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"view-more\">\r\n");
      out.write("                <a href=\"#\" class=\"btn\">더 많은 여행지 보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"news\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"section-title\">항공사 소식</h2>\r\n");
      out.write("            <div class=\"news-grid\">\r\n");
      out.write("                <div class=\"news-card\">\r\n");
      out.write("                    <div class=\"news-img\" style=\"background-image: url('https://images.unsplash.com/photo-1436491865332-7a61a109cc05?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"news-content\">\r\n");
      out.write("                        <span class=\"news-date\">2023.07.15</span>\r\n");
      out.write("                        <h3>신규 노선 오픈 안내</h3>\r\n");
      out.write("                        <p>2023년 9월부터 새롭게 선보이는 대양주 노선에 대한 안내입니다.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"read-more\">자세히 보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"news-card\">\r\n");
      out.write("                    <div class=\"news-img\" style=\"background-image: url('https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"news-content\">\r\n");
      out.write("                        <span class=\"news-date\">2023.07.08</span>\r\n");
      out.write("                        <h3>프리미엄 기내식 리뉴얼</h3>\r\n");
      out.write("                        <p>최고의 셰프와 협업한 새로운 기내식 메뉴를 소개합니다.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"read-more\">자세히 보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"news-card\">\r\n");
      out.write("                    <div class=\"news-img\" style=\"background-image: url('https://images.unsplash.com/photo-1530521954074-e64f6810b32d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');\"></div>\r\n");
      out.write("                    <div class=\"news-content\">\r\n");
      out.write("                        <span class=\"news-date\">2023.07.01</span>\r\n");
      out.write("                        <h3>여름 시즌 특별 프로모션</h3>\r\n");
      out.write("                        <p>여름 휴가철 맞이 특별 할인 프로모션을 확인하세요.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"read-more\">자세히 보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"view-more\">\r\n");
      out.write("                <a href=\"#\" class=\"btn\">모든 소식 보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 모듈화된 푸터 포함 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
